In [2]:
import pandas as pd

In [3]:
spotify = pd.read_csv('spotify.csv', sep=',')
spotify

,Unnamed: 0,id,name,genre,album,popularity,duration_ms,explicit,Artist_1,Artist_2,Artist_3,Artist_4,Artist_5,Artist_6,Artist_7,Artist_8,Artist_9,Artist_10,Artist_11
0,0,7kr3xZk4yb3YSZ4VFtg2Qt,Acoustic,acoustic,1975,58,172199,False,Billy Raffoul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1kJygfS4eoVziBBI93MSYp,Acoustic,acoustic,A Few More Hours at YYZ,57,172202,False,Billy Raffoul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6lynns69p4zTCRxmmiSY1x,Here Comes the Sun - Acoustic,acoustic,Here Comes the Sun,42,144786,False,Molly Hocking,Bailey Rushlow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1RC9slv335IfLce5vt9KTW,Acoustic #3,acoustic,Dizzy up the Girl,46,116573,False,The Goo Goo Dolls,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5o9L8xBuILoVjLECSBi7Vo,My Love Mine All Mine - Acoustic Instrumental,acoustic,My Love Mine All Mine,33,133922,False,Guus Dielissen,Casper Esmann,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6295,6295,4uveHSzaz8YEbTF9j6QlCI,Voyage to Atlantis,world-music,Reign of Vengeance,25,180001,False,Future World Music,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6296,6296,4u15cjyziW2Ewn5Ek3082l,L'Oiseau,world-music,Global Relaxation by Putumayo,25,276776,False,Putumayo,Marianne Perrudin,Thomas Artaud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6297,6297,56pHPaTeX2O9aVmTFYS8hV,The Daintree,world-music,World Music,12,69533,False,Joseph Tawadros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6298,6298,6Ldyc5TsR4kaUsuHKcB2AD,The Sorcerers Symphony,world-music,Behold,26,90001,False,Future World Music,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6299,6299,3ry0f8ybk8upUBIk8unvmF,Fiore d'inverno,world-music,World Party 5 by Putumayo,25,141800,False,Putumayo,Giacomo Lariccia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
artists_expanded = spotify['artists'].str.split(r'\s*,\s*', expand=True)

In [4]:
artists_expanded.columns = [f'Artist_{i+1}' for i in range(artists_expanded.shape[1])]

In [5]:
spotify = pd.concat([spotify, artists_expanded], axis=1)

In [6]:
spotify

,id,name,genre,artists,album,popularity,duration_ms,explicit,Artist_1,Artist_2,Artist_3,Artist_4,Artist_5,Artist_6,Artist_7,Artist_8,Artist_9,Artist_10,Artist_11
0,7kr3xZk4yb3YSZ4VFtg2Qt,Acoustic,acoustic,Billy Raffoul,1975,58,172199,False,Billy Raffoul,None,None,None,None,None,None,None,None,None,None
1,1kJygfS4eoVziBBI93MSYp,Acoustic,acoustic,Billy Raffoul,A Few More Hours at YYZ,57,172202,False,Billy Raffoul,None,None,None,None,None,None,None,None,None,None
2,6lynns69p4zTCRxmmiSY1x,Here Comes the Sun - Acoustic,acoustic,"Molly Hocking, Bailey Rushlow",Here Comes the Sun (Acoustic),42,144786,False,Molly Hocking,Bailey Rushlow,None,None,None,None,None,None,None,None,None
3,1RC9slv335IfLce5vt9KTW,Acoustic #3,acoustic,The Goo Goo Dolls,Dizzy up the Girl,46,116573,False,The Goo Goo Dolls,None,None,None,None,None,None,None,None,None,None
4,5o9L8xBuILoVjLECSBi7Vo,My Love Mine All Mine - Acoustic Instrumental,acoustic,"Guus Dielissen, Casper Esmann",My Love Mine All Mine (Acoustic Instrumental),33,133922,False,Guus Dielissen,Casper Esmann,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6295,4uveHSzaz8YEbTF9j6QlCI,Voyage to Atlantis,world-music,Future World Music,Reign of Vengeance,25,180001,False,Future World Music,None,None,None,None,None,None,None,None,None,None
6296,4u15cjyziW2Ewn5Ek3082l,L'Oiseau,world-music,"Putumayo, Marianne Perrudin, Thomas Artaud",Global Relaxation by Putumayo,25,276776,False,Putumayo,Marianne Perrudin,Thomas Artaud,None,None,None,None,None,None,None,None
6297,56pHPaTeX2O9aVmTFYS8hV,The Daintree,world-music,Joseph Tawadros,World Music,12,69533,False,Joseph Tawadros,None,None,None,None,None,None,None,None,None,None
6298,6Ldyc5TsR4kaUsuHKcB2AD,The Sorcerers Symphony,world-music,Future World Music,Behold,26,90001,False,Future World Music,None,None,None,None,None,None,None,None,None,None
6299,3ry0f8ybk8upUBIk8unvmF,Fiore d'inverno,world-music,"Putumayo, Giacomo Lariccia",World Party 5 by Putumayo,25,141800,False,Putumayo,Giacomo Lariccia,None,None,None,None,None,None,None,None,None

In [7]:
spotify['album'] = spotify['album'].str.replace(r'\(.*?\)', '', regex=True).str.strip()

In [8]:
spotify

,id,name,genre,artists,album,popularity,duration_ms,explicit,Artist_1,Artist_2,Artist_3,Artist_4,Artist_5,Artist_6,Artist_7,Artist_8,Artist_9,Artist_10,Artist_11
0,7kr3xZk4yb3YSZ4VFtg2Qt,Acoustic,acoustic,Billy Raffoul,1975,58,172199,False,Billy Raffoul,None,None,None,None,None,None,None,None,None,None
1,1kJygfS4eoVziBBI93MSYp,Acoustic,acoustic,Billy Raffoul,A Few More Hours at YYZ,57,172202,False,Billy Raffoul,None,None,None,None,None,None,None,None,None,None
2,6lynns69p4zTCRxmmiSY1x,Here Comes the Sun - Acoustic,acoustic,"Molly Hocking, Bailey Rushlow",Here Comes the Sun,42,144786,False,Molly Hocking,Bailey Rushlow,None,None,None,None,None,None,None,None,None
3,1RC9slv335IfLce5vt9KTW,Acoustic #3,acoustic,The Goo Goo Dolls,Dizzy up the Girl,46,116573,False,The Goo Goo Dolls,None,None,None,None,None,None,None,None,None,None
4,5o9L8xBuILoVjLECSBi7Vo,My Love Mine All Mine - Acoustic Instrumental,acoustic,"Guus Dielissen, Casper Esmann",My Love Mine All Mine,33,133922,False,Guus Dielissen,Casper Esmann,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6295,4uveHSzaz8YEbTF9j6QlCI,Voyage to Atlantis,world-music,Future World Music,Reign of Vengeance,25,180001,False,Future World Music,None,None,None,None,None,None,None,None,None,None
6296,4u15cjyziW2Ewn5Ek3082l,L'Oiseau,world-music,"Putumayo, Marianne Perrudin, Thomas Artaud",Global Relaxation by Putumayo,25,276776,False,Putumayo,Marianne Perrudin,Thomas Artaud,None,None,None,None,None,None,None,None
6297,56pHPaTeX2O9aVmTFYS8hV,The Daintree,world-music,Joseph Tawadros,World Music,12,69533,False,Joseph Tawadros,None,None,None,None,None,None,None,None,None,None
6298,6Ldyc5TsR4kaUsuHKcB2AD,The Sorcerers Symphony,world-music,Future World Music,Behold,26,90001,False,Future World Music,None,None,None,None,None,None,None,None,None,None
6299,3ry0f8ybk8upUBIk8unvmF,Fiore d'inverno,world-music,"Putumayo, Giacomo Lariccia",World Party 5 by Putumayo,25,141800,False,Putumayo,Giacomo Lariccia,None,None,None,None,None,None,None,None,None

In [12]:
spotify = spotify.drop(columns=['artists'])

In [13]:
spotify

,id,name,genre,album,popularity,duration_ms,explicit,Artist_1,Artist_2,Artist_3,Artist_4,Artist_5,Artist_6,Artist_7,Artist_8,Artist_9,Artist_10,Artist_11
0,7kr3xZk4yb3YSZ4VFtg2Qt,Acoustic,acoustic,1975,58,172199,False,Billy Raffoul,None,None,None,None,None,None,None,None,None,None
1,1kJygfS4eoVziBBI93MSYp,Acoustic,acoustic,A Few More Hours at YYZ,57,172202,False,Billy Raffoul,None,None,None,None,None,None,None,None,None,None
2,6lynns69p4zTCRxmmiSY1x,Here Comes the Sun - Acoustic,acoustic,Here Comes the Sun,42,144786,False,Molly Hocking,Bailey Rushlow,None,None,None,None,None,None,None,None,None
3,1RC9slv335IfLce5vt9KTW,Acoustic #3,acoustic,Dizzy up the Girl,46,116573,False,The Goo Goo Dolls,None,None,None,None,None,None,None,None,None,None
4,5o9L8xBuILoVjLECSBi7Vo,My Love Mine All Mine - Acoustic Instrumental,acoustic,My Love Mine All Mine,33,133922,False,Guus Dielissen,Casper Esmann,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6295,4uveHSzaz8YEbTF9j6QlCI,Voyage to Atlantis,world-music,Reign of Vengeance,25,180001,False,Future World Music,None,None,None,None,None,None,None,None,None,None
6296,4u15cjyziW2Ewn5Ek3082l,L'Oiseau,world-music,Global Relaxation by Putumayo,25,276776,False,Putumayo,Marianne Perrudin,Thomas Artaud,None,None,None,None,None,None,None,None
6297,56pHPaTeX2O9aVmTFYS8hV,The Daintree,world-music,World Music,12,69533,False,Joseph Tawadros,None,None,None,None,None,None,None,None,None,None
6298,6Ldyc5TsR4kaUsuHKcB2AD,The Sorcerers Symphony,world-music,Behold,26,90001,False,Future World Music,None,None,None,None,None,None,None,None,None,None
6299,3ry0f8ybk8upUBIk8unvmF,Fiore d'inverno,world-music,World Party 5 by Putumayo,25,141800,False,Putumayo,Giacomo Lariccia,None,None,None,None,None,None,None,None,None

In [15]:
spotify['Artist_2'].hasnans

False

In [14]:
spotify['Artist_2'] = spotify['Artist_2'].fillna('None')

In [18]:
spotify['Artist_3'].hasnans

False

In [17]:
spotify['Artist_3'] = spotify['Artist_3'].fillna('None')

In [20]:
spotify['Artist_4'].hasnans

False

In [19]:
spotify['Artist_4'] = spotify['Artist_4'].fillna('None')

In [22]:
spotify['Artist_5'].hasnans

False

In [21]:
spotify['Artist_5'] = spotify['Artist_5'].fillna('None')

In [24]:
spotify['Artist_6'].hasnans

False

In [23]:
spotify['Artist_6'] = spotify['Artist_6'].fillna('None')

In [26]:
spotify['Artist_7'].hasnans

False

In [25]:
spotify['Artist_7'] = spotify['Artist_7'].fillna('None')

In [28]:
spotify['Artist_8'].hasnans

False

In [27]:
spotify['Artist_8'] = spotify['Artist_8'].fillna('None')

In [30]:
spotify['Artist_9'].hasnans

False

In [29]:
spotify['Artist_9'] = spotify['Artist_9'].fillna('None')

In [32]:
spotify['Artist_10'].hasnans

False

In [31]:
spotify['Artist_10'] = spotify['Artist_10'].fillna('None')

In [34]:
spotify['Artist_11'].hasnans

False

In [33]:
spotify['Artist_11'] = spotify['Artist_11'].fillna('None')

In [35]:
spotify.to_csv('spotify.csv')